apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-ui
          env:
          - name: MINIO_HOST
            value: rook-ceph-rgw-minio.rook-ceph.svc.cluster.local
          - name: MINIO_PORT
            value: "80"
