apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: profile-controller
          env:
          - name: MINIO_HOST
            value: rook-ceph-rgw-minio.rook-ceph.svc.cluster.local
          - name: MINIO_PORT
            value: "80"
          - name: MINIO_NAMESPACE
            value: ""
