apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
          - name: OBJECTSTORECONFIG_HOST
            value: rook-ceph-rgw-minio.rook-ceph.svc.cluster.local
