apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: minio
  namespace: rook-ceph # namespace:cluster
spec:
  metadataPool:
    replicated:
      size: 3
  dataPool:
    replicated:
      size: 3
  preservePoolsOnDelete: false
  gateway:
    port: 80
    # securePort: 443
    instances: 1

